### ISSUE TITLE
npm ERR! 404 Not Found 

### ISSUE THREAD

**Issue by liyejun** [DeborahK/Angular-ReactiveForms#20]
npm ERR! 404 Not Found - GET https://registry.npmjs.org/es-abstract/-/es-abstract-1.14.0.tgz

**Comment by DeborahK** [comment]
Can you provide more context? When do you see this error?

**Comment by liyejun** [comment]
I checked the versions of es-abstract, 1.14.0 isn't there. I just used 1.14.1 or 1.14.2 instead, then  problem got fixed.
https://www.npmjs.com/package/es-abstract

**Comment by DeborahK** [comment]
I have removed the package-lock.json file from the APM folder (assuming that is what you are installing?) Let me know if that helps as well.
